### ISSUE TITLE
Not Impled: 로그인하면 초기에 유저 정보를 못 들고옴

### ISSUE THREAD

**Issue by eunoiahyunseo** [eunoiahyunseo/foreign-student-support#2]
- [x] HomeView에서 onAppear할 때 비동기로 getUser정보를 FireAuth에서 받아온 id로 받아온다 -> API구현 해야함

**Comment by ChangeMaker13** [comment]
로그인할때마다 국가 적어줘야하는 것도 이문제 때문인지 모르겠으나, 해당 이슈 있음.
